[project]
name = "price-comparison"
version = "0.1.0"
description = "basic streamlit app for price comparison"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.52.2",
    "plotly>=5.14.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
]
